//
//  CountriesRouter.swift
//  SimpleCustoms
//
//  Created Газияв Исхаков on 31.01.2020.
//  Copyright © 2020 Газияв Исхаков. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CountriesRouter: CountriesWireframeInput {

    weak var viewController: UIViewController?

    func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CountriesViewController(nibName: nil, bundle: nil)
        let interactor = CountriesInteractor()
        let router = CountriesRouter()
        let presenter = CountriesPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        
        router.viewController = view

        return view
    }
}
