//
//  CountriesRouter.swift
//  SimpleCustoms
//
//  Created Газияв Исхаков on 31.01.2020.
//  Copyright © 2020 Газияв Исхаков. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CountriesRouter: CountriesRouterInput {

   // var appRouter: AppRouterProtocol?
    
    func performTransitionToCustoms(data: CustomsRules) {

        AppRouter.shared.performTransition(to: .customs(rules: data))
    }
}
