//
//  CountriesProtocols.swift
//  SimpleCustoms
//
//  Created Газияв Исхаков on 31.01.2020.
//  Copyright © 2020 Газияв Исхаков. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

protocol CountriesInteractorOutputProtocol: class {
    func obtainCountriesSuccess(countries: [Country]?)
    func obtainCountriesFailure()
    func didGetCustomsRules(rules: CustomsRules)
    /* Interactor -> Presenter */
}

protocol CountriesInteractorInputProtocol: class {

    var presenter: CountriesInteractorOutputProtocol?  { get set }
    
    func fetchCountries(for regions: [Regions])
    func rulesForCountry(country: Country)
    /* Presenter -> Interactor */
}


