//
//  CountriesProtocols.swift
//  SimpleCustoms
//
//  Created Газияв Исхаков on 31.01.2020.
//  Copyright © 2020 Газияв Исхаков. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -

//MARK: Presenter -


//MARK: Interactor -
protocol CountriesInteractorOutputProtocol: class {
    func obtainCountriesSuccess(countries: [Country])
    func obtainCountriesFailure()
    /* Interactor -> Presenter */
}

protocol CountriesInteractorInputProtocol: class {

    var presenter: CountriesInteractorOutputProtocol?  { get set }
    
    func fetchCountries() 
    
    /* Presenter -> Interactor */
}

//MARK: View -

