//
//  CustomsRouter.swift
//  SimpleCustoms
//
//  Created Газияв Исхаков on 05.02.2020.
//  Copyright © 2020 Газияв Исхаков. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CustomsRouter: CustomsWireframeProtocol {

    var appRouter: AppRouterProtocol?
    
    
}
