//
//  CustomsViewController.swift
//  SimpleCustoms
//
//  Created Газияв Исхаков on 05.02.2020.
//  Copyright © 2020 Газияв Исхаков. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RealmSwift

class CustomsViewController: UIViewController, CustomsViewProtocol {
    
    var presenter: CustomsPresenterProtocol?
    
    var rules: CustomsRules? {
        didSet {
            flagImage.image = UIImage(named: rules?.forCountryCode?.lowercased() ?? "")
            //descriptionView.infoForCell = rules
        }
    }
    
    private var flagImage: UIImageView = {
        let imageView = UIImageView()
        imageView.translatesAutoresizingMaskIntoConstraints = false
        return imageView
    }()
    
    private let descriptionView: CountryDescriptionView = {
        let view = CountryDescriptionView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    private let rulesView: CustomsRulesView = {
        let view = CustomsRulesView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    private let containterView = UIView()
    private let scrollView = UIScrollView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupNavigationController()
        setupScrollView()
        setupUIElementsInView()
        
    }
    
    override func viewDidLayoutSubviews() {
        scrollView.layoutIfNeeded()
        scrollView.contentSize.height = descriptionView.frame.height + rulesView.frame.height + flagImage.frame.height + 75
    }
    
    private func setupScrollView() {
        
        scrollView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(scrollView)
        scrollView.edgesToSuperview()
    }
    
    private func setupRulesView() {
        containterView.addSubview(rulesView)
        rulesView.dataSource = self
        
        NSLayoutConstraint.activate([
            
            rulesView.topAnchor.constraint(equalTo: descriptionView.bottomAnchor, constant: 30),
            rulesView.leadingAnchor.constraint(equalTo: containterView.leadingAnchor,constant: 15),
            rulesView.trailingAnchor.constraint(equalTo: containterView.trailingAnchor, constant: -15),
            rulesView.heightAnchor.constraint(equalToConstant: view.frame.height)
            
        ])
    }
    
    private func setupNavigationController() {
        if #available(iOS 13.0, *) {
            view.backgroundColor = .secondarySystemBackground
        } else {
            view.backgroundColor = #colorLiteral(red: 0.8588235294, green: 0.8862745098, blue: 0.9137254902, alpha: 1)
        }
        navigationItem.largeTitleDisplayMode = .always
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationController?.navigationBar.shadowImage = UIImage()
        navigationController?.navigationBar.topItem?.title = ""
    }
    
    private func setupUIElementsInView() {
        containterView.translatesAutoresizingMaskIntoConstraints = false
        scrollView.addSubview(containterView)
        containterView.edgesToSuperview()
        containterView.centerInSuperview()
        
        setupImage()
        setupDescriptionView()
        setupRulesView()
    }
    
    private func setupImage() {
        containterView.addSubview(flagImage)
        
        flagImage.top(to: containterView.safeAreaLayoutGuide, offset: 8)
        flagImage.leading(to: containterView, offset: 18)
        flagImage.width(250)
        flagImage.height(170)
        
        flagImage.layer.cornerRadius = 10
        flagImage.layer.masksToBounds = true
    }
    
    private func setupDescriptionView() {
        containterView.addSubview(descriptionView)
        
        descriptionView.leading(to: containterView, offset: 25)
        descriptionView.topToBottom(of: flagImage, offset: 15)
        descriptionView.trailing(to: containterView, offset: -25)
        descriptionView.height(150)
    }
}


extension CustomsViewController: RulesCellDataSource {
    func defineContentForCell() -> List<CustomsRuleDescription> {
        
        return rules?.customsRule ?? List<CustomsRuleDescription>()
    }
}
